# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-08 17:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0013_notification'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notification',
            new_name='NotificationModel',
        ),
    ]
